include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/generated/**"
    - "**/*.g.dart"
    - "android/**"
    - "ios/**"
    - "linux/**"
    - "macos/**"
    - "windows/**"

linter:
  rules:
    # Keep default rules; can add project-specific toggles below.
    # prefer_single_quotes: true
